config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'
  get '/admin/tests/:id/update_inline', to: 'admin/tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :feed_backs, only: [:new, :create]

  resources :tests, only: :index do
    
    member do
      post :start
    end
  end
  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end
  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :bages
    resources :bages_rules
  end
  resources :gists, only: :index
  resources :bages, only: [:index] do
      get :bages_by_user, on: :collection
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  
  scope :correct_answers, -> { where(correct: true) }
  
  private
  
  def validate_max_answers
    errors.add(:max_answers, 'too many answers') if question.answers.count > 4
  end

end

app/models/bage.rb
class Bage < ApplicationRecord
  has_many :bages_rules, dependent: :destroy
  has_many :bage_users, dependent: :destroy
  has_many :users, through: :bage_users
end

app/models/bage_user.rb
class BageUser < ApplicationRecord
  belongs_to :bage
  belongs_to :user
end

app/models/bages_rule.rb
class BagesRule < ApplicationRecord
  belongs_to :bage
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  
  has_many :tests

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  
  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages#, source: :user
  
  belongs_to :category
  belongs_to :author, foreign_key: "user_id" , class_name: "User", optional: true
  
  validates :title, presence: true
  validates :level, numericality: { only_integer: true }
  validates :title, uniqueness: { scope: :level }

  scope :easy_level, -> { where(level: 0..1).order(created_at: :desc) }
  scope :average_level, -> { where(level: 2..4).order(created_at: :desc) }
  scope :difficult_level, -> { where(level: 5..Float::INFINITY).order(created_at: :desc) }
  scope :categories, -> (category) { joins(:category).where("categories.title like ? ", category) }
  
  def self.levels(level)
    where(level: level).order(id: :asc).pluck(:id)
  end

  def self.categories_desc_title(category)
    categories(category).order(:title, :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85

  has_many :bages_users, dependent: :destroy
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, foreign_key: 'question_id', class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  after_validation :after_validation_next_question, on: :update, if: ->  { !completed? }

  scope :test_is_success, -> { where(success_test: true) }

  def self.test_attempt(test_id, user)
    test_is_success.where(user_id: user.id, test_id: test_id).count
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    if completed? && success?
      self.success_test = true
    end
    save
  end

  def completed?
    current_question.nil?
  end

  def success?
    result > SUCCESS_PERCENT
  end

  def result
    correct_questions * 100 / test.questions.count
  end

  def number_of_questions
    test.questions.order(id: :asc).where('id < ?', question_id).count + 1
  end

  def timer_is_over?
    return false if test.timer == 0
    delta_time >= test.timer
  end

  def delta_time
    Time.now.to_i - self.created_at.to_i
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def after_validation_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) && 
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :trackable,
          :validatable,
          :confirmable

  # include Auth

  has_many :test_passages
  has_many :gists
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: "Test", foreign_key: :user_id
  has_many :bages
  has_many :bage_users, dependent: :destroy
  has_many :bages, through: :bage_users

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def levels(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.class == Admin
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/bages_helper.rb
module BagesHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/feed_backs_helper.rb
module FeedBacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    question.persisted? ? "Edit #{question.test.title} Question" : "Create New #{question.test.title} Question"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard  }.freeze
  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_nav.html.erb
<div class="nav nav-admin">
  <span class="nav-admin title">TestGuru <%= t('.header') %></span>
  <div class='nav-admin user'>
    <%= link_to 'TestGuru', root_path %>
    <%= t('.welcome') %>, <b class="nav-admin user-email"><%= current_user.email %></b> Guru | 
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <%= link_to t('.admin'), admin_tests_path, class: "btn btn-outline-warning" %>
    <%= link_to t('.gist'), gists_path, class: "btn btn-outline-warning" %>
  </div>
</div>

app/views/layouts/_futter.html.erb
<%# <div class="justify-content-center mt-3"> %>
  <%# <div class="col col-md-4"> %>
  <div class="card border-primary">
      <div class="card-body">
      
      <p class="center_position"><%= year %>год <%= github_url('Сытин Николай Борисович', 'https://github.com/kokdot') %> </p>

      <p class="center_position"> Данный проект реализует учебную задачу по тестированию пользователей в различных областях знаний.</p>

      <p class="center_position"><%= link_to 'Учебный проект в онлайн-школе Thinknetica', "http://thinknetica.com", target: "_blank" %></p>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div id="navbar">
      <p class='nav user'>
        <%= link_to 'TestGuru', root_path %>
        <% if user_signed_in?%>
          <%= t('.welcome') %>, <b><%= current_user.email %></b> Guru | 
          <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign up',  new_user_registration_path %> | <%= link_to 'Login', new_user_session_path %>
        <% end %>
      </p>
    </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.header') %> | Testguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/nav' %>
      <%= render 'shared/flash' %>

      <%= yield %>
      <%= render 'layouts/futter' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Testguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container">
      <%= render 'shared/nav' %>
      <%= render 'shared/flash' %>

      <%= yield %>
      <%= render 'layouts/futter' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: {  resource_id: resource.id} do %>
    <h2><%= t('.header', count: resource.errors.count) %>: </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, sanitize(message), class: "#{flash_class(key)}" %>
<% end %>

app/views/shared/_nav.html.erb
<div class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <% if user_signed_in?%>
      <%= t('.welcome') %>, <b><%= current_user.email %></b> Guru | 
      <%= link_to t('.bages'), bages_path, class: "btn btn-outline-success" %> | 
      <%= link_to t('.my_bages'), bages_by_user_bages_path, class: "btn btn-outline-success" %> | 
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %> | 
      <% if current_user.admin?%>
        <%= link_to t('.admin'), admin_tests_path, class: "btn btn-outline-warning" %>
        <%= link_to t('.gist'), gists_path, class: "btn btn-outline-warning" %>
      <% end %>
      <%= link_to 'feedback', new_feed_back_path, class: "btn btn-outline-success" %>
    <% else %>
      <%= link_to t('.sign_up'),  new_user_registration_path, class: "btn btn-outline-success" %> | 
      <%= link_to t('.login'), new_user_session_path, class: "btn btn-outline-success" %>
    <% end %>
  </span>
</div>