config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'
  get '/admin/tests/:id/update_inline', to: 'admin/tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :feed_backs, only: [:new, :create]

  resources :tests, only: :index do
    
    member do
      post :start
    end
  end
  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end
  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :bages
    resources :bages_rules
  end
  resources :gists, only: :index
  resources :bages, only: [:index] do
      get :bages_by_user, on: :collection
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  
  scope :correct_answers, -> { where(correct: true) }
  
  private
  
  def validate_max_answers
    errors.add(:max_answers, 'too many answers') if question.answers.count > 4
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bage.rb
class Bage < ApplicationRecord
  has_many :bages_rules, dependent: :destroy
  has_many :bage_users, dependent: :destroy
  has_many :users, through: :bage_users
end

app/models/bage_user.rb
class BageUser < ApplicationRecord
  belongs_to :bage
  belongs_to :user
end

app/models/bages_rule.rb
class BagesRule < ApplicationRecord
  belongs_to :bage
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  
  has_many :tests

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  
  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages#, source: :user
  
  belongs_to :category
  belongs_to :author, foreign_key: "user_id" , class_name: "User", optional: true
  
  validates :title, presence: true
  validates :level, numericality: { only_integer: true }
  validates :title, uniqueness: { scope: :level }

  scope :easy_level, -> { where(level: 0..1).order(created_at: :desc) }
  scope :average_level, -> { where(level: 2..4).order(created_at: :desc) }
  scope :difficult_level, -> { where(level: 5..Float::INFINITY).order(created_at: :desc) }
  scope :categories, -> (category) { joins(:category).where("categories.title like ? ", category) }
  
  def self.levels(level)
    where(level: level).order(id: :asc).pluck(:id)
  end

  def self.categories_desc_title(category)
    categories(category).order(:title, :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85

  has_many :bages_users, dependent: :destroy
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, foreign_key: 'question_id', class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  after_validation :after_validation_next_question, on: :update, if: ->  { !completed? }

  scope :test_is_success, -> { where(success_test: true) }

  def self.test_attempt(test_id, user)
    test_is_success.where(user_id: user.id, test_id: test_id).count
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    if completed? && success?
      self.success_test = true
    end
    save
  end

  def completed?
    current_question.nil?
  end

  def success?
    result > SUCCESS_PERCENT
  end

  def result
    correct_questions * 100 / test.questions.count
  end

  def number_of_questions
    test.questions.order(id: :asc).where('id < ?', question_id).count + 1
  end

  def timer_is_over?
    return false if test.timer == 0
    delta_time >= test.timer
  end

  def delta_time
    Time.now.to_i - self.created_at.to_i
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def after_validation_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) && 
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :trackable,
          :validatable,
          :confirmable

  # include Auth

  has_many :test_passages
  has_many :gists
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: "Test", foreign_key: :user_id
  has_many :bages
  has_many :bage_users, dependent: :destroy
  has_many :bages, through: :bage_users

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def levels(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.class == Admin
  end
end

app/controllers/admin/bages_rules_controller.rb
class Admin::BagesRulesController < ApplicationController
  before_action :set_bages_rule, except: [:index, :new, :create]
  def index
    @bages_rules = BagesRule.all
  end

  def new
    @bages_rule = BagesRule.new
  end

  def create
    @bages_rule = BagesRule.new(bages_rule_params)
    if @bages_rule.save
      redirect_to [:admin, @bages_rule], notice: t('.success')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @bages_rule.update(bages_rule_params)
      redirect_to [:admin, @bages_rule]
    else
      render :edit
    end
  end

  def destroy
    @bages_rule.destroy
    redirect_to admin_bages_rules_path
  end

  private

  def bages_rule_params
    params.require(:bages_rule).permit(:rule, :bage_id, :description)
  end

  def set_bages_rule
    @bages_rule = BagesRule.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/bages_helper.rb
module BagesHelper
end

app/helpers/bages_rules_helper.rb
module BagesRulesHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/feed_backs_helper.rb
module FeedBacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    question.persisted? ? "Edit #{question.test.title} Question" : "Create New #{question.test.title} Question"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard  }.freeze
  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/bages_rules/_bages_rule.html.erb
<tr>
  <td class="align-middle"><%= bages_rule.id %></td>
  <td class="sort align-middle">
    <%= bage.rule %>
  </td>
  <td class="align-middle"><%= bages_rule.bage.title %></td>
  <td class="align-middle"><%= bages_rule.description %></td>

  <td class="align-middle"><%= link_to t('.show'), admin_bages_rule_path(bages_rule), class: "btn btn-outline-primary" %></td>
  <td class="align-middle"><%= link_to t('.edit'), 
                              edit_admin_bages_rule_path(bages_rule), 
                              class: "btn btn-outline-secondary form-inline-link" %>
  </td>
  <td class="align-middle"><%= link_to t('.delete'), 
                              admin_bages_rule_path(bages_rule), 
                              method: :delete, data: { confirm: 'A you sure?' }, 
                              class: "btn btn-outline-danger" %>
  </td>
</tr>

app/views/admin/bages_rules/_form.html.erb
<%= form_with model: [:admin, @bages_rule], local: true do |form| %>
  <%= render 'shared/errors', resource: @bages_rule  %>
  
  <p>
    <%= form.label :rule %>
    <%= form.text_field :rule %>
  </p>

  <p>
    <%= form.label :bage_id %>: 
    <%= form.collection_select :bage_id, Bage.all, :id, :title, prompt: true  %>
  </p>

  <p>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </p>
  <%= form.submit %>
<% end %>

app/views/admin/bages_rules/edit.html.erb
<h1>Edit BagesRule: <br><%= @bages_rule.title %></h1>
<%= render 'form' %>
<%= link_to 'Back', admin_bages_rules_path %>

app/views/admin/bages_rules/index.html.erb
<h1><%= t('.header') %></h1>
<p>
  <%= link_to t('.new'), new_admin_bages_rule_path, class: "btn btn-primary" %>
</p>

  <%= render 'shared/errors', resource: @bages_rule  %>

<table class= "table">
  <tr>
    <th scope="col"><%= t('.id') %></th>
    <th scope="col", class="sort-by-title pointer">
      <%= t('.rule') %>
      <%= octicon 'arrow-up', class: 'text-success hide' %>
      <%= octicon 'arrow-down', class: 'text-success hide' %>
    </th>
    <th scope="col"><%= t('.bage_id') %></th>
    <th scope="col"><%= t('.description') %></th>
    <th scope="col" colspan="3"><%= t('.action') %></th>
  </tr>
  <%= render @bages_rules %>
</table>

app/views/admin/bages_rules/new.html.erb
<h><%= t('.header') %></h>
<%= render 'form' %>
<%= link_to 'Back', admin_bages_rules_path %>

app/views/admin/bages_rules/show.html.erb
<p>
  <strong>Rule: </strong>
  <%= @bages_rule.rule %>
</p>

<p>
  <strong>Bage title: </strong>
  <%= @bages_rule.bage.title %>
</p>

<p>
  <strong>Description title: </strong>
  <%= @bages_rule.description %>
</p>

<%= link_to 'Edit', edit_admin_bages_rule_path(@bages_rule) %> |
<%= link_to 'Back', admin_bages_rules_path %>